In [1]:
import pandas as pd
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn import set_config; set_config(display='diagram')

from xgboost import XGBClassifier

In [2]:
from src.utils import load_data, evaluate

In [3]:
def load_trained_artifacts():
    """
    Loads saved processor, model and pipeline

    """
    BASE_PATH = '../../models/'
    preproc_path = BASE_PATH +'xgb_churn_preproc_pipeline.pkl'
    model_path = BASE_PATH + 'xgb_churn_model.pkl'
    full_pipeline_path = BASE_PATH +'xgb_churn_pipeline.pkl'

    #Load artifacts from memory
    print("🔄 Loading pipeline components, preprocessor and model...")
    preprocessor = joblib.load(preproc_path)
    model = joblib.load(model_path)
    print("🔄 Loading full pipeline...")
    pipeline = joblib.load(full_pipeline_path)

    print("✅ Artifacts successfully loaded!")
    return preprocessor, model, pipeline

In [4]:
preprocessor, model, pipeline = load_trained_artifacts()

🔄 Loading pipeline components, preprocessor and model...
🔄 Loading full pipeline...
✅ Artifacts successfully loaded!

In [5]:
X_val = load_data('../../data/X_val_xgb.csv')
y_val = load_data('../../data/y_val_xgb.csv')

In [6]:
X_val.head()

,account_age,monthly_charges,total_charges,viewing_hours_per_week,average_viewing_duration,content_downloads_per_month,user_rating,support_tickets_per_month,watchlist_size,subscription_type_Basic,...,genre_preference_Comedy,genre_preference_Drama,genre_preference_Fantasy,genre_preference_Sci-Fi,gender_Female,gender_Male,parental_control_No,parental_control_Yes,subtitles_enabled_No,subtitles_enabled_Yes
0,-0.846477,1.473174,-0.315354,-0.001546,1.240065,-0.174380,-0.849460,1.568181,1.526467,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,-0.758913,1.119614,-0.306662,1.378156,-1.087942,0.172433,0.075705,0.523659,1.526467,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.817249,-1.654959,-0.538483,-0.784522,-1.374945,0.172433,1.548561,-1.217210,1.109519,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,-0.671348,0.772547,-0.313552,-0.337176,-0.150572,-0.451830,1.309454,0.871833,-0.141326,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.992379,-0.864404,0.138111,-0.195809,1.323928,1.212871,-1.148239,-0.172688,1.387484,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
y_val.head()

   churn
0      0
1      0
2      0
3      1
4      0

In [8]:
evaluate(pipeline, X_val, y_val)

================ MODEL PERFORMANCE ================
              precision    recall  f1-score   support

           0       0.83      0.98      0.90     39922
           1       0.57      0.11      0.18      8836

    accuracy                           0.82     48758
   macro avg       0.70      0.54      0.54     48758
weighted avg       0.79      0.82      0.77     48758

ROC-AUC Score: 0.7466
============================================= =======