In [1]:
import pandas as pd
import seaborn as sns
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn import set_config; set_config(display='diagram')

from xgboost import XGBClassifier

In [2]:
from utils import load_data, evaluate

In [3]:
def load_trained_artifacts():
    """
    Loads saved processor, model and pipeline
    """
    #Load artifacts from memory
    print("🔄 Loading components: preprocessor and model...")
    preprocessor = joblib.load(os.environ["MODEL_NAME_PREPROCESSOR"])
    model = joblib.load(os.environ["MODEL_NAME_XGB"])

    print("✅ Artifacts successfully loaded!")
    return preprocessor, model

In [4]:
preprocessor, model = load_trained_artifacts()

🔄 Loading components: preprocessor and model...
✅ Artifacts successfully loaded!

In [ ]:
file_path_X = f'''{os.path.dirname(os.path.dirname(__file__))}/data/X.csv'''
file_path_y = f'''{os.path.dirname(os.path.dirname(__file__))}/data/y.csv'''
X_val = load_data(file_path_X)
y_val = load_data(file_path_y)

In [6]:
X_val.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled
0,31,18.871369,585.012434,Basic,Mailed check,No,Movies,Yes,Computer,20.515996,154.972317,22,Action,2.026801,9,Female,23,No,Yes
1,34,17.339934,589.557749,Premium,Bank transfer,No,Both,No,Computer,36.016501,37.410487,27,Action,3.093885,6,Female,23,No,Yes
2,88,5.321946,468.331228,Premium,Bank transfer,No,TV Shows,Yes,TV,11.719514,22.917143,27,Action,4.792676,1,Male,20,No,No
3,37,15.836623,585.955056,Premium,Electronic check,Yes,Both,No,TV,16.745304,84.746628,18,Fantasy,4.516890,7,Male,11,Yes,Yes
4,94,8.746215,822.144229,Basic,Bank transfer,Yes,Movies,No,Computer,18.333511,159.207305,42,Fantasy,1.682190,4,Male,22,Yes,No

In [7]:
y_val.head()

   Churn
0      0
1      0
2      0
3      1
4      0

In [8]:
evaluate(preprocessor, model, X_val, y_val)

================ MODEL PERFORMANCE ================
              precision    recall  f1-score   support

           0       0.83      0.98      0.90     39922
           1       0.57      0.11      0.18      8836

    accuracy                           0.82     48758
   macro avg       0.70      0.54      0.54     48758
weighted avg       0.79      0.82      0.77     48758

ROC-AUC Score: 0.7466
============================================= =======

(array([0, 0, 0, ..., 0, 0, 0], shape=(48758,)),
 array([0.346462  , 0.2498818 , 0.09865487, ..., 0.37843138, 0.3671446 ,
        0.12476036], shape=(48758,), dtype=float32))