In [1]:
import pandas as pd
import seaborn as sns
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn import set_config; set_config(display='diagram')

from xgboost import XGBClassifier

In [2]:
from utils import load_data, evaluate

In [3]:
def load_trained_artifacts():
    """
    Loads saved processor, model and pipeline
    """
    #Load artifacts from memory
    print("🔄 Loading components: preprocessor and model...")
    preprocessor = joblib.load(os.environ["MODEL_PATH"]+'xgb_churn_preproc_pipeline.pkl')
    model = joblib.load(os.environ["MODEL_PATH"]+ 'xgb_churn_model.pkl')

    print("✅ Artifacts successfully loaded!")
    return preprocessor, model

In [4]:
preprocessor, model = load_trained_artifacts()

🔄 Loading components: preprocessor and model...
✅ Artifacts successfully loaded!

In [5]:
X_val = load_data(os.environ["VALIDATION_DATA_X"])
y_val = load_data(os.environ["VALIDATION_DATA_Y"])

In [6]:
X_val.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,SubscriptionType_Basic,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,-0.846477,1.473174,-0.315354,-0.001546,1.240065,-0.174380,-0.849460,1.568181,1.526467,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,-0.758913,1.119614,-0.306662,1.378156,-1.087942,0.172433,0.075705,0.523659,1.526467,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.817249,-1.654959,-0.538483,-0.784522,-1.374945,0.172433,1.548561,-1.217210,1.109519,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,-0.671348,0.772547,-0.313552,-0.337176,-0.150572,-0.451830,1.309454,0.871833,-0.141326,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.992379,-0.864404,0.138111,-0.195809,1.323928,1.212871,-1.148239,-0.172688,1.387484,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
y_val.head()

   Churn
0      0
1      0
2      0
3      1
4      0

In [8]:
evaluate(preprocessor, model, X_val, y_val)

================ MODEL PERFORMANCE ================
              precision    recall  f1-score   support

           0       0.83      0.98      0.90     39922
           1       0.57      0.11      0.18      8836

    accuracy                           0.82     48758
   macro avg       0.70      0.54      0.54     48758
weighted avg       0.79      0.82      0.77     48758

ROC-AUC Score: 0.7466
============================================= =======

(array([0, 0, 0, ..., 0, 0, 0], shape=(48758,)),
 array([0.346462  , 0.2498818 , 0.09865487, ..., 0.37843138, 0.3671446 ,
        0.12476036], shape=(48758,), dtype=float32))